import mongoose from 'mongoose';

const productSchema = new mongoose.Schema(
  {
    code: { type: String, unique: true },
    name: String,
    nameUr: String,
    summary: String,
    family: { type: String, enum: ['conventional', 'islamic'] },
    contractType: String,
    jurisdiction: { type: String, default: 'PK' },
    currency: { type: String, default: 'PKR' },
    segments: [String],
    employment: [String],
    minAmount: Number,
    maxAmount: Number,
    minTenor: Number,
    maxTenor: Number,
    baseRate: Number,
    minRate: Number,
    maxRate: Number,
    feeRate: { type: Number, default: 0 },
    lgd: { type: Number, default: 0.45 },
    affordabilityMode: { type: String, default: 'dbr' },
    allowExpat: { type: Boolean, default: false },
    stpEligible: { type: Boolean, default: false },
    latePaymentCharity: { type: Boolean, default: false },
    accent: { type: String, default: 'ink' },
    status: { type: String, default: 'active' },
    displayGroup: String,
    financingType: String,
    channels: [String],
    showInCatalogue: { type: Boolean, default: true },
    amountStep: Number,
    tenorStep: Number,
    defaultAmount: Number,
    defaultTenor: Number,
    repaymentMode: String,
    minIncome: Number,
    minAge: Number,
    maxAge: Number,
    maxAgeAtMaturity: Number,
    downPaymentMin: Number,
    maxLtv: Number,
    feeMin: Number,
    feeMax: Number,
    residualRate: Number,
    stpLimit: Number,
    pricingBasis: String,
    profitMethod: String,
    ruleSetId: String,
    scorecardId: String,
    pricingTableId: String,
    workflowId: String,
    doaMatrixId: String,
    documentPackId: String,
    kfsTemplateId: String,
    contractTemplateId: String,
    shariahProfileId: String,
    glPool: String,
    temenosProduct: String,
    badge: String,
    phase: Number,
  },
  { timestamps: true },
);

export const Product = mongoose.model('Product', productSchema);
