import mongoose from 'mongoose';

const productSchema = new mongoose.Schema(
  {
    code: { type: String, unique: true },
    name: String,
    nameUr: String,
    summary: String,
    family: { type: String, default: 'PERSONAL' },
    contractType: String,
    jurisdiction: { type: String, default: 'PK' },
    currency: { type: String, default: 'PKR' },
    segments: [String],
    employment: [String],
    minAmount: Number,
    maxAmount: Number,
    minTenor: Number,
    maxTenor: Number,
    baseRate: Number,
    minRate: Number,
    maxRate: Number,
    feeRate: { type: Number, default: 0 },
    lgd: { type: Number, default: 0.45 },
    affordabilityMode: { type: String, default: 'dbr' },
    allowExpat: { type: Boolean, default: false },
    stpEligible: { type: Boolean, default: false },
    latePaymentCharity: { type: Boolean, default: false },
    accent: { type: String, default: 'ink' },
    status: { type: String, default: 'active' },
    displayGroup: String,
    financingType: String,
    channels: [String],
    showInCatalogue: { type: Boolean, default: true },
    amountStep: Number,
    tenorStep: Number,
    defaultAmount: Number,
    defaultTenor: Number,
    repaymentMode: String,
    minIncome: Number,
    minAge: Number,
    maxAge: Number,
    maxAgeAtMaturity: Number,
    downPaymentMin: Number,
    maxLtv: Number,
    feeMin: Number,
    feeMax: Number,
    residualRate: Number,
    stpLimit: Number,
    pricingBasis: String,
    profitMethod: String,
    ruleSetId: String,
    scorecardId: String,
    pricingTableId: String,
    workflowId: String,
    doaMatrixId: String,
    documentPackId: String,
    kfsTemplateId: String,
    contractTemplateId: String,
    shariahProfileId: String,
    glPool: String,
    temenosProduct: String,
    badge: String,
    phase: Number,
    shortCode: String,
    structure: String,
    segment: String,
    variant: String,
    names: mongoose.Schema.Types.Mixed,
    amount: mongoose.Schema.Types.Mixed,
    tenor: mongoose.Schema.Types.Mixed,
    pricing: mongoose.Schema.Types.Mixed,
    repayment: mongoose.Schema.Types.Mixed,
    fees: { type: [mongoose.Schema.Types.Mixed], default: [] },
    insurance: mongoose.Schema.Types.Mixed,
    eligibilityRuleCodes: [String],
    policyRuleCodes: [String],
    scorecardCode: String,
    documentRequirements: { type: [mongoose.Schema.Types.Mixed], default: [] },
    integrationPlan: { type: [mongoose.Schema.Types.Mixed], default: [] },
    workflowCode: String,
    glTemplateCode: String,
    presentation: mongoose.Schema.Types.Mixed,
    servicing: mongoose.Schema.Types.Mixed,
    draftStep: Number,
    effectiveFrom: Date,
    effectiveTo: Date,
    version: { type: Number, default: 1 },
    deletedAt: Date,
    deletedBy: String,
  },
  { timestamps: true, strict: false },
);

export const Product = mongoose.model('Product', productSchema);
