import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import { env } from './config/env.js';
import { rejectOperators, requireClientHeader } from './security/auth.js';
import { errorHandler, notFound } from './middleware/errorHandler.js';
import identityRoutes from './modules/identity/routes/identityRoutes.js';
import customerRoutes from './modules/customers/routes/customerRoutes.js';
import productRoutes from './modules/products/routes/productRoutes.js';
import configurationRoutes from './modules/configuration/routes/configurationRoutes.js';
import scorecardRoutes from './modules/scorecards/routes/scorecardRoutes.js';
import ruleRoutes from './modules/rules/routes/ruleRoutes.js';
import applicationRoutes from './modules/applications/routes/applicationRoutes.js';
import engagementRoutes from './modules/engagement/routes/engagementRoutes.js';
import servicingRoutes from './modules/servicing/routes/servicingRoutes.js';
import documentRoutes from './modules/documents/routes/documentRoutes.js';
import complianceRoutes from './modules/compliance/routes/complianceRoutes.js';
import reportingRoutes from './modules/reporting/routes/reportingRoutes.js';
import dealerRoutes from './modules/dealers/routes/dealerRoutes.js';
import earlyWarningRoutes from './modules/earlywarning/routes/earlyWarningRoutes.js';
import modelRiskRoutes from './modules/modelrisk/routes/modelRiskRoutes.js';
import schemeRoutes from './modules/schemes/routes/schemeRoutes.js';
import integrationRoutes from './modules/integrations/routes/integrationRoutes.js';
import adminRoutes from './routes/adminRoutes.js';
import configRoutes from './routes/configRoutes.js';
import channelRoutes from './routes/channelRoutes.js';
import opsRoutes from './routes/opsRoutes.js';

export function createApp() {
  const app = express();
  app.disable('x-powered-by');
  app.use(helmet());
  app.use(cors({ origin: env.clientOrigin, credentials: true }));
  app.use(express.json({ limit: '1mb' }));
  app.use(cookieParser());
  app.use(rejectOperators);
  app.use(requireClientHeader);
  app.get('/api/health', (req, res) => {
    res.json({ ok: true, service: 'lending-platform', demoMode: env.demoMode });
  });
  const opsPrefixes = ['/dashboard', '/queue', '/applications', '/customers', '/loans', '/gl', '/eod', '/collections', '/reports', '/complaints', '/integrations', '/audit', '/provisioning'];
  app.use('/api', (req, res, next) => {
    if (opsPrefixes.some((prefix) => req.path === prefix || req.path.startsWith(`${prefix}/`))) return opsRoutes(req, res, next);
    return next();
  });
  app.use('/api/admin', adminRoutes);
  app.use('/api/config', configRoutes);
  app.use('/api/channel', channelRoutes);
  app.use('/api/identity', identityRoutes);
  app.use('/api/customers', customerRoutes);
  app.use('/api/products', productRoutes);
  app.use('/api/configuration', configurationRoutes);
  app.use('/api/scorecards', scorecardRoutes);
  app.use('/api/rules', ruleRoutes);
  app.use('/api/applications', applicationRoutes);
  app.use('/api/engagement', engagementRoutes);
  app.use('/api/servicing', servicingRoutes);
  app.use('/api/documents', documentRoutes);
  app.use('/api/compliance', complianceRoutes);
  app.use('/api/reporting', reportingRoutes);
  app.use('/api/dealers', dealerRoutes);
  app.use('/api/early-warning', earlyWarningRoutes);
  app.use('/api/model-risk', modelRiskRoutes);
  app.use('/api/schemes', schemeRoutes);
  app.use('/api/integrations', integrationRoutes);
  app.use(notFound);
  app.use(errorHandler);
  return app;
}
