import mongoose from 'mongoose';

const loanSchema = new mongoose.Schema(
  {
    tenantId: String,
    applicationId: { type: mongoose.Schema.Types.ObjectId },
    customerId: { type: mongoose.Schema.Types.ObjectId, index: true },
    productCode: String,
    contractType: String,
    currency: { type: String, default: 'PKR' },
    principal: Number,
    rate: Number,
    tenorMonths: Number,
    instalment: Number,
    status: { type: String, default: 'active' },
    disbursedAt: Date,
    accountMasked: String,
    rail: { type: String, default: 'Raast' },
    nextDebitDay: { type: Number, default: 5 },
    schedule: { type: [mongoose.Schema.Types.Mixed], default: [] },
    paidCount: { type: Number, default: 0 },
    loanAccountNo: { type: String, unique: true, sparse: true },
    productVersion: Number,
    branchId: String,
    entityId: { type: String, default: 'PK-01' },
    sanctionedAmount: Number,
    disbursedAmount: Number,
    rateType: String,
    firstDueDate: String,
    maturityDate: String,
    repaymentMode: String,
    mandateId: String,
    balances: { type: mongoose.Schema.Types.Mixed, default: {} },
    dpd: { type: Number, default: 0 },
    bucket: { type: String, default: 'Current' },
    maxDpd: { type: Number, default: 0 },
    regulatoryClassification: { type: String, default: 'Regular' },
    ifrs9Stage: { type: Number, default: 1 },
    eclAmount: { type: Number, default: 0 },
    regulatoryProvision: { type: Number, default: 0 },
    bookedProvision: { type: Number, default: 0 },
    restructured: { type: Boolean, default: false },
    writeOff: { type: mongoose.Schema.Types.Mixed, default: {} },
    scheduleVersion: { type: Number, default: 1 },
    frozen: { type: Boolean, default: false },
    islamic: { type: Boolean, default: false },
    version: { type: Number, default: 1 },
    feesDue: { type: Number, default: 0 },
    lateChargesDue: { type: Number, default: 0 },
    interestDue: { type: Number, default: 0 },
    interestOverdue: { type: Number, default: 0 },
    interestAccrued: { type: Number, default: 0 },
    interestSuspended: { type: Number, default: 0 },
    principalDue: { type: Number, default: 0 },
    principalOverdue: { type: Number, default: 0 },
    principalOutstanding: { type: Number, default: 0 },
    excessPayment: { type: Number, default: 0 },
    charityPayable: { type: Number, default: 0 },
    lateChargeApplied: { type: Boolean, default: false },
  },
  { timestamps: true },
);

export const LoanAccount = mongoose.model('LoanAccount', loanSchema);

const requestSchema = new mongoose.Schema(
  {
    tenantId: String,
    loanId: { type: mongoose.Schema.Types.ObjectId, index: true },
    customerId: { type: mongoose.Schema.Types.ObjectId },
    type: { type: String, enum: ['topup', 'prepay', 'restructure'] },
    amount: Number,
    tenorMonths: Number,
    status: { type: String, default: 'submitted' },
    decision: { type: mongoose.Schema.Types.Mixed },
    preview: { type: mongoose.Schema.Types.Mixed },
  },
  { timestamps: true },
);

export const ServicingRequest = mongoose.model('ServicingRequest', requestSchema);
