const channels = ['mobile', 'internet', 'branch', 'rm', 'contact_centre', 'dealer'];
const retailAge = { minAge: 21, maxAge: 60, maxAgeAtMaturity: 65 };

function product(partial) {
  return {
    jurisdiction: 'PK',
    currency: 'PKR',
    status: 'active',
    channels,
    showInCatalogue: true,
    amountStep: 5000,
    tenorStep: 6,
    repaymentMode: 'auto_debit',
    lgd: 0.45,
    phase: 1,
    ...partial,
  };
}

export const HBL_CODES = {
  PL: 'HBL-CON-PER-01',
  IPF: 'HBL-ISL-PER-01',
  AL: 'HBL-CON-AUT-01',
  AI: 'HBL-ISL-AUT-01',
  HL: 'HBL-CON-HOM-01',
  HD: 'HBL-ISL-HOM-01',
  SW: 'HBL-CON-SME-01',
  SM: 'HBL-ISL-SME-01',
};

export const hblProducts = [
  product({
    code: HBL_CODES.PL,
    name: 'HBL Personal Loan',
    nameUr: 'ایچ بی ایل پرسنل لون',
    summary: 'Unsecured personal finance. The monthly payment and total cost are shown before you apply.',
    family: 'conventional',
    contractType: 'conventional',
    financingType: 'personal',
    displayGroup: 'Personal',
    segments: ['salaried', 'self_employed', 'expat'],
    employment: ['salaried', 'self_employed'],
    minAmount: 50000,
    maxAmount: 3000000,
    defaultAmount: 800000,
    minTenor: 12,
    maxTenor: 60,
    defaultTenor: 36,
    baseRate: 0.15,
    minRate: 0.12,
    maxRate: 0.22,
    feeRate: 0.01,
    feeMin: 2500,
    feeMax: 25000,
    minIncome: 40000,
    ...retailAge,
    affordabilityMode: 'dbr',
    stpEligible: true,
    stpLimit: 1500000,
    pricingBasis: 'benchmark_plus_spread',
    ruleSetId: 'RS-RET-PL',
    scorecardId: 'SC-RET-UNS',
    pricingTableId: 'PT-PL',
    workflowId: 'WF-RET-STD',
    doaMatrixId: 'DOA-RET',
    documentPackId: 'DP-PL',
    kfsTemplateId: 'KFS-PL',
    contractTemplateId: 'CT-PL',
    glPool: 'CONV',
    temenosProduct: 'HBL.PL.TERM',
    badge: 'Popular',
    accent: 'ink',
  }),
  product({
    code: HBL_CODES.IPF,
    name: 'HBL Islamic Personal Finance',
    nameUr: 'ایچ بی ایل اسلامی پرسنل فنانس',
    summary: 'Murabaha: the bank buys the asset, then sells it to you at a disclosed cost plus profit.',
    family: 'islamic',
    contractType: 'murabaha',
    financingType: 'personal',
    displayGroup: 'Personal',
    segments: ['salaried', 'self_employed', 'expat'],
    employment: ['salaried', 'self_employed'],
    minAmount: 50000,
    maxAmount: 3000000,
    defaultAmount: 800000,
    minTenor: 12,
    maxTenor: 60,
    defaultTenor: 36,
    baseRate: 0.09,
    minRate: 0.07,
    maxRate: 0.14,
    feeRate: 0.01,
    feeMin: 2500,
    feeMax: 25000,
    minIncome: 40000,
    ...retailAge,
    affordabilityMode: 'dbr',
    stpEligible: true,
    stpLimit: 1500000,
    latePaymentCharity: true,
    pricingBasis: 'profit_rate',
    profitMethod: 'flat',
    ruleSetId: 'RS-RET-IPF',
    scorecardId: 'SC-RET-UNS',
    pricingTableId: 'PT-IPF',
    workflowId: 'WF-RET-STD',
    doaMatrixId: 'DOA-RET',
    documentPackId: 'DP-IPF',
    kfsTemplateId: 'KFS-IPF',
    contractTemplateId: 'CT-IPF',
    shariahProfileId: 'SH-MUR',
    glPool: 'ISL',
    temenosProduct: 'HBL.IPF.MUR',
    badge: 'Islamic',
    accent: 'pine',
  }),
  product({
    code: HBL_CODES.AL,
    name: 'HBL Auto Loan',
    nameUr: 'ایچ بی ایل آٹو لون',
    summary: 'Vehicle finance with a down payment, hypothecation and comprehensive insurance.',
    family: 'conventional',
    contractType: 'conventional',
    financingType: 'auto',
    displayGroup: 'Vehicle',
    segments: ['salaried', 'self_employed', 'expat'],
    employment: ['salaried', 'self_employed'],
    minAmount: 500000,
    maxAmount: 10000000,
    defaultAmount: 2000000,
    minTenor: 12,
    maxTenor: 84,
    defaultTenor: 36,
    baseRate: 0.16,
    minRate: 0.12,
    maxRate: 0.22,
    feeRate: 0.01,
    minIncome: 60000,
    downPaymentMin: 0.15,
    maxLtv: 0.85,
    ...retailAge,
    affordabilityMode: 'dbr',
    stpEligible: true,
    stpLimit: 3000000,
    pricingBasis: 'benchmark_plus_spread',
    ruleSetId: 'RS-RET-AL',
    scorecardId: 'SC-RET-AST',
    pricingTableId: 'PT-AL',
    workflowId: 'WF-RET-AST',
    doaMatrixId: 'DOA-RET',
    documentPackId: 'DP-AL',
    kfsTemplateId: 'KFS-AL',
    contractTemplateId: 'CT-AL',
    glPool: 'CONV',
    temenosProduct: 'HBL.AL.TERM',
    phase: 1,
    accent: 'ink',
  }),
  product({
    code: HBL_CODES.AI,
    name: 'HBL Islamic Auto Ijarah',
    nameUr: 'ایچ بی ایل آٹو اجارہ',
    summary: 'The bank owns the vehicle and leases it to you. Takaful and possession are evidenced before rentals start.',
    family: 'islamic',
    contractType: 'ijarah',
    financingType: 'auto',
    displayGroup: 'Vehicle',
    segments: ['salaried', 'self_employed', 'expat'],
    employment: ['salaried', 'self_employed'],
    minAmount: 500000,
    maxAmount: 10000000,
    defaultAmount: 2000000,
    minTenor: 12,
    maxTenor: 84,
    defaultTenor: 36,
    baseRate: 0.16,
    minRate: 0.12,
    maxRate: 0.22,
    feeRate: 0.01,
    minIncome: 60000,
    downPaymentMin: 0.15,
    maxLtv: 0.85,
    residualRate: 0,
    ...retailAge,
    affordabilityMode: 'dbr',
    stpEligible: true,
    stpLimit: 3000000,
    latePaymentCharity: true,
    pricingBasis: 'rental_rate',
    profitMethod: 'rental',
    ruleSetId: 'RS-RET-AI',
    scorecardId: 'SC-RET-AST',
    pricingTableId: 'PT-AI',
    workflowId: 'WF-RET-AST-ISL',
    doaMatrixId: 'DOA-RET',
    documentPackId: 'DP-AI',
    kfsTemplateId: 'KFS-AI',
    contractTemplateId: 'CT-AI',
    shariahProfileId: 'SH-IJR',
    glPool: 'ISL',
    temenosProduct: 'HBL.AI.IJR',
    badge: 'Islamic',
    accent: 'brass',
  }),
  product({
    code: HBL_CODES.HL,
    name: 'HBL Home Loan',
    nameUr: 'ایچ بی ایل ہوم لون',
    summary: 'A home loan against a registered mortgage, with valuation and legal opinion on the path.',
    family: 'conventional',
    contractType: 'conventional',
    financingType: 'home',
    displayGroup: 'Home',
    segments: ['salaried', 'self_employed', 'expat'],
    employment: ['salaried', 'self_employed'],
    minAmount: 1000000,
    maxAmount: 50000000,
    defaultAmount: 5000000,
    minTenor: 60,
    maxTenor: 300,
    defaultTenor: 180,
    tenorStep: 12,
    baseRate: 0.14,
    minRate: 0.1,
    maxRate: 0.2,
    feeRate: 0.01,
    minIncome: 80000,
    maxLtv: 0.7,
    ...retailAge,
    allowExpat: true,
    affordabilityMode: 'dbr',
    stpEligible: false,
    stpLimit: 0,
    pricingBasis: 'benchmark_plus_spread',
    ruleSetId: 'RS-RET-HL',
    scorecardId: 'SC-RET-MTG',
    pricingTableId: 'PT-HL',
    workflowId: 'WF-RET-MTG',
    doaMatrixId: 'DOA-MTG',
    documentPackId: 'DP-HL',
    kfsTemplateId: 'KFS-HL',
    contractTemplateId: 'CT-HL',
    glPool: 'CONV',
    temenosProduct: 'HBL.HL.TERM',
    phase: 2,
    accent: 'ink',
  }),
  product({
    code: HBL_CODES.HD,
    name: 'HBL Islamic Home Finance',
    nameUr: 'ایچ بی ایل اسلامی ہوم فنانس',
    summary: 'Diminishing Musharakah: you and the bank co-own the home, and you buy the bank’s units over time.',
    family: 'islamic',
    contractType: 'diminishing_musharakah',
    financingType: 'home',
    displayGroup: 'Home',
    segments: ['salaried', 'self_employed', 'expat'],
    employment: ['salaried', 'self_employed'],
    minAmount: 1000000,
    maxAmount: 50000000,
    defaultAmount: 5000000,
    minTenor: 60,
    maxTenor: 300,
    defaultTenor: 180,
    tenorStep: 12,
    baseRate: 0.14,
    minRate: 0.1,
    maxRate: 0.2,
    feeRate: 0.01,
    minIncome: 80000,
    maxLtv: 0.7,
    ...retailAge,
    allowExpat: true,
    affordabilityMode: 'dbr',
    stpEligible: false,
    stpLimit: 0,
    latePaymentCharity: true,
    pricingBasis: 'rental_rate',
    profitMethod: 'diminishing_musharakah',
    ruleSetId: 'RS-RET-HD',
    scorecardId: 'SC-RET-MTG',
    pricingTableId: 'PT-HD',
    workflowId: 'WF-RET-MTG-ISL',
    doaMatrixId: 'DOA-MTG',
    documentPackId: 'DP-HD',
    kfsTemplateId: 'KFS-HD',
    contractTemplateId: 'CT-HD',
    shariahProfileId: 'SH-DM',
    glPool: 'ISL',
    temenosProduct: 'HBL.HD.DM',
    badge: 'Islamic',
    phase: 2,
    accent: 'pine',
  }),
  product({
    code: HBL_CODES.SW,
    name: 'HBL SME Working Capital',
    nameUr: 'ایچ بی ایل ایس ایم ای ورکنگ کیپیٹل',
    summary: 'A renewable running-finance limit for a trading business, priced on the amount drawn.',
    family: 'conventional',
    contractType: 'running_finance',
    financingType: 'working_capital',
    displayGroup: 'Business',
    segments: ['sme'],
    employment: ['self_employed'],
    minAmount: 500000,
    maxAmount: 100000000,
    defaultAmount: 5000000,
    minTenor: 12,
    maxTenor: 12,
    defaultTenor: 12,
    tenorStep: 12,
    baseRate: 0.18,
    minRate: 0.14,
    maxRate: 0.26,
    feeRate: 0.01,
    lgd: 0.4,
    affordabilityMode: 'cashflow',
    stpEligible: false,
    stpLimit: 0,
    pricingBasis: 'benchmark_plus_spread',
    ruleSetId: 'RS-SME-SW',
    scorecardId: 'SC-SME-OBL',
    pricingTableId: 'PT-SW',
    workflowId: 'WF-SME',
    doaMatrixId: 'DOA-SME',
    documentPackId: 'DP-SW',
    kfsTemplateId: 'KFS-SW',
    contractTemplateId: 'CT-SW',
    glPool: 'CONV',
    temenosProduct: 'HBL.SME.RF',
    phase: 3,
    accent: 'ink',
  }),
  product({
    code: HBL_CODES.SM,
    name: 'HBL Islamic SME Running Musharakah',
    nameUr: 'ایچ بی ایل رننگ مشارکت',
    summary: 'A revolving partnership limit. Profit is shared on the method approved for the product.',
    family: 'islamic',
    contractType: 'running_musharakah',
    financingType: 'working_capital',
    displayGroup: 'Business',
    segments: ['sme'],
    employment: ['self_employed'],
    minAmount: 500000,
    maxAmount: 100000000,
    defaultAmount: 5000000,
    minTenor: 12,
    maxTenor: 12,
    defaultTenor: 12,
    tenorStep: 12,
    baseRate: 0.18,
    minRate: 0.14,
    maxRate: 0.26,
    feeRate: 0.01,
    lgd: 0.4,
    affordabilityMode: 'cashflow',
    stpEligible: false,
    stpLimit: 0,
    latePaymentCharity: true,
    pricingBasis: 'expected_profit',
    profitMethod: 'running_musharakah',
    ruleSetId: 'RS-SME-SM',
    scorecardId: 'SC-SME-OBL',
    pricingTableId: 'PT-SM',
    workflowId: 'WF-SME-ISL',
    doaMatrixId: 'DOA-SME',
    documentPackId: 'DP-SM',
    kfsTemplateId: 'KFS-SM',
    contractTemplateId: 'CT-SM',
    shariahProfileId: 'SH-RMU',
    glPool: 'ISL',
    temenosProduct: 'HBL.SME.RMU',
    badge: 'Islamic',
    phase: 3,
    accent: 'brass',
  }),
];
