/** Permission catalogue (FSD 5.2). Synced into Mongo on startup. */

export const PERMISSIONS = [
  ['dashboard:view', 'dashboard', 'view', 'Open the back-office dashboard', 'Dashboard', false],
  ['application:view', 'application', 'view', 'View applications', 'Origination', false],
  ['application:create', 'application', 'create', 'Create an application', 'Origination', false],
  ['application:edit', 'application', 'edit', 'Edit application data', 'Origination', false],
  ['application:submit', 'application', 'submit', 'Submit an application', 'Origination', false],
  ['application:assign', 'application', 'assign', 'Assign a case to yourself', 'Origination', false],
  ['application:reassign', 'application', 'reassign', 'Reassign a case', 'Origination', false],
  ['application:recommend', 'application', 'recommend', 'Record a recommendation', 'Origination', false],
  ['application:approve', 'application', 'approve', 'Approve an application', 'Origination', true],
  ['application:decline', 'application', 'decline', 'Decline an application', 'Origination', true],
  ['application:return', 'application', 'return', 'Return an application', 'Origination', false],
  ['application:cancel', 'application', 'cancel', 'Cancel an application', 'Origination', false],
  ['application:override_rule', 'application', 'override_rule', 'Approve or reject a deviation', 'Origination', true],
  ['application:view_bureau', 'application', 'view_bureau', 'View the full bureau report', 'Origination', true],
  ['application:view_full_pii', 'application', 'view_full_pii', 'View full applicant identity numbers', 'Origination', true],
  ['application:export', 'application', 'export', 'Export applications', 'Origination', false],
  ['customer:view', 'customer', 'view', 'View customers', 'Customers', false],
  ['customer:create', 'customer', 'create', 'Create a customer', 'Customers', false],
  ['customer:edit', 'customer', 'edit', 'Edit a customer', 'Customers', false],
  ['customer:merge', 'customer', 'merge', 'Merge customer records', 'Customers', true],
  ['customer:view_full_pii', 'customer', 'view_full_pii', 'View full customer identity numbers', 'Customers', true],
  ['customer:mark_negative_list', 'customer', 'mark_negative_list', 'Place a customer on the negative list', 'Customers', true],
  ['document:view', 'document', 'view', 'View documents', 'Documents', false],
  ['document:upload', 'document', 'upload', 'Upload documents', 'Documents', false],
  ['document:verify', 'document', 'verify', 'Verify or reject documents', 'Documents', false],
  ['document:delete', 'document', 'delete', 'Delete documents', 'Documents', false],
  ['document:download', 'document', 'download', 'Download documents', 'Documents', true],
  ['collateral:view', 'collateral', 'view', 'View collateral', 'Collateral', false],
  ['collateral:create', 'collateral', 'create', 'Add collateral', 'Collateral', false],
  ['collateral:edit', 'collateral', 'edit', 'Edit collateral', 'Collateral', false],
  ['collateral:mark_lien', 'collateral', 'mark_lien', 'Mark a lien', 'Collateral', true],
  ['collateral:release_lien', 'collateral', 'release_lien', 'Release a lien', 'Collateral', true],
  ['collateral:revalue', 'collateral', 'revalue', 'Revalue collateral', 'Collateral', false],
  ['disbursement:initiate', 'disbursement', 'initiate', 'Prepare a disbursement', 'Disbursement', false],
  ['disbursement:authorise', 'disbursement', 'authorise', 'Authorise a disbursement', 'Disbursement', true],
  ['disbursement:reverse', 'disbursement', 'reverse', 'Reverse a disbursement', 'Disbursement', true],
  ['loan:view', 'loan', 'view', 'View loan accounts', 'Servicing', false],
  ['loan:reschedule', 'loan', 'reschedule', 'Reschedule a loan', 'Servicing', true],
  ['loan:restructure', 'loan', 'restructure', 'Restructure a loan', 'Servicing', true],
  ['loan:prepay', 'loan', 'prepay', 'Post a prepayment', 'Servicing', false],
  ['loan:waive_charges', 'loan', 'waive_charges', 'Waive charges', 'Servicing', true],
  ['loan:change_rate', 'loan', 'change_rate', 'Change a rate', 'Servicing', true],
  ['loan:freeze', 'loan', 'freeze', 'Freeze a loan', 'Servicing', true],
  ['loan:close', 'loan', 'close', 'Close a loan', 'Servicing', true],
  ['loan:write_off', 'loan', 'write_off', 'Write off a loan', 'Servicing', true],
  ['loan:write_back', 'loan', 'write_back', 'Write back a recovery', 'Servicing', true],
  ['repayment:post', 'repayment', 'post', 'Post a repayment', 'Servicing', false],
  ['repayment:reverse', 'repayment', 'reverse', 'Reverse a repayment', 'Servicing', true],
  ['repayment:allocate_manual', 'repayment', 'allocate_manual', 'Allocate a payment manually', 'Servicing', true],
  ['collection:view', 'collection', 'view', 'View collection cases', 'Collections', false],
  ['collection:act', 'collection', 'act', 'Log a collection action', 'Collections', false],
  ['collection:assign', 'collection', 'assign', 'Assign a collection case', 'Collections', false],
  ['collection:settle_propose', 'collection', 'settle_propose', 'Propose a settlement', 'Collections', false],
  ['collection:settle_approve', 'collection', 'settle_approve', 'Approve a settlement', 'Collections', true],
  ['collection:legal_initiate', 'collection', 'legal_initiate', 'Initiate legal action', 'Collections', true],
  ['collection:repossess', 'collection', 'repossess', 'Repossess collateral', 'Collections', true],
  ['gl:view', 'gl', 'view', 'View the general ledger', 'Accounting', false],
  ['gl:manual_journal', 'gl', 'manual_journal', 'Create a manual journal', 'Accounting', true],
  ['gl:approve_journal', 'gl', 'approve_journal', 'Approve a manual journal', 'Accounting', true],
  ['gl:eod_run', 'gl', 'eod_run', 'Run end of day', 'Accounting', true],
  ['gl:period_close', 'gl', 'period_close', 'Close an accounting period', 'Accounting', true],
  ['provision:view', 'provision', 'view', 'View provisioning', 'Provisioning', false],
  ['provision:run', 'provision', 'run', 'Run provisioning', 'Provisioning', true],
  ['provision:override_classification', 'provision', 'override_classification', 'Override a classification', 'Provisioning', true],
  ['provision:approve_override', 'provision', 'approve_override', 'Approve a classification override', 'Provisioning', true],
  ['product:view', 'product', 'view', 'View products', 'Product factory', false],
  ['product:create', 'product', 'create', 'Create a product', 'Product factory', false],
  ['product:edit', 'product', 'edit', 'Edit a product', 'Product factory', false],
  ['product:publish', 'product', 'publish', 'Publish a product', 'Product factory', true],
  ['product:retire', 'product', 'retire', 'Retire a product', 'Product factory', true],
  ['config:view', 'config', 'view', 'View configuration', 'Configuration', false],
  ['config:edit', 'config', 'edit', 'Edit configuration', 'Configuration', false],
  ['config:publish', 'config', 'publish', 'Publish configuration', 'Configuration', true],
  ['rbac:view', 'rbac', 'view', 'View access control', 'Access', false],
  ['rbac:manage_roles', 'rbac', 'manage_roles', 'Manage roles', 'Access', true],
  ['rbac:manage_users', 'rbac', 'manage_users', 'Manage users', 'Access', true],
  ['rbac:reset_mfa', 'rbac', 'reset_mfa', 'Reset multi-factor authentication', 'Access', true],
  ['rbac:unlock', 'rbac', 'unlock', 'Unlock a user', 'Access', true],
  ['integration:view_logs', 'integration', 'view_logs', 'View integration logs', 'Integrations', false],
  ['integration:configure', 'integration', 'configure', 'Configure integrations', 'Integrations', true],
  ['integration:test', 'integration', 'test', 'Send a test integration call', 'Integrations', false],
  ['report:view', 'report', 'view', 'View reports', 'Reports', false],
  ['report:schedule', 'report', 'schedule', 'Schedule reports', 'Reports', false],
  ['report:export', 'report', 'export', 'Export reports', 'Reports', false],
  ['audit:view', 'audit', 'view', 'View the audit log', 'Audit', false],
  ['audit:export', 'audit', 'export', 'Export the audit log', 'Audit', true],
];

export const PERMISSION_CODES = PERMISSIONS.map(([code]) => code);

export function permissionRecords() {
  return PERMISSIONS.map(([code, resource, action, description, module, isSensitive]) => ({
    code, resource, action, description, module, isSensitive,
  }));
}
